apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
    type: frontend
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - name: "result-service"
      port: 8081
      nodePort: 31001
      targetPort: 80
  
