apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote
    type: frontend
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - name: vote-service
      port: 8080
      nodePort: 31000
      targetPort: 80

