apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: worker
    type: worker
spec:
  template:
    metadata:
      name: worker-app
      labels:
        app: worker
        type: worker
    spec:
      containers:
        - name: worker-app
          image: worker-app
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      resources:
        limits:
          cpu: "2"
          memory: 100Mi
        requests:
          cpu: "0.2"
          memory: 50Mi
  selector:
    matchLabels:
      app: worker
  replicas: 1

    